### ISSUE TITLE
프록시 서버 통신 404 Error - CORS, 동일 출처 정책

### ISSUE THREAD

**Issue by dusunax** [Broccoli-Velog/Broccoli-Frontend#11]
- **에러코드A** to "/register", Code 404
![image](https://user-images.githubusercontent.com/94776135/181865496-37840590-c19f-419a-b45b-ae66da901e16.png)

- **에러코드B** to "http://localhost:4000/register", CORS policy
![image](https://user-images.githubusercontent.com/94776135/181865587-2832dd0c-11cd-4c56-916a-f1c9aef8ad84.png)

---
구글링  

https://jrepository.tistory.com/58
- package.json에 `"proxy": "http://localhost:4000"`
- **currently** 라이브러리   

https://okky.kr/article/1177877
- **http-proxy-middleware** 패키지
- setProxy.js 설정
---
ENV파일 통일 후 에러
![image](https://user-images.githubusercontent.com/94776135/181909716-c01d8c5c-b29c-4bac-bec6-569a24fdf003.png)

**Comment by somfist** [comment]
AxiosError {message: 'Unsupported protocol localhost:', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}}
code: "ERR_BAD_REQUEST"
config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
message: "Unsupported protocol localhost:"
name: "AxiosError"
[[Prototype]]: Error
![image](https://user-images.githubusercontent.com/89966037/181917532-272df5ab-2a40-41ee-ba08-94ec1b39bae9.png)

**Comment by somfist** [comment]
Access to XMLHttpRequest at 'localhost:4000/' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

Error: Network Error
at createError (createError.js:16:1)
at XMLHttpRequest.handleError (xhr.js:117:1)

xhr.js:210 POST localhost:4000/ net::ERR_FAILED
![image](https://user-images.githubusercontent.com/89966037/181917554-5408121c-7296-4622-aeb5-232338225cae.png)

**Comment by unchaptered** [comment]
[axios 2.7.1 이후부터 요청 경로에 콜론(:) 이 있으면 에러 발생](https://okky.kr/article/1213494)
[CORS 오류: "요청은 프로토콜 체계에 대해서만 지원됩니다: http..." 등](https://stackoverflow.com/questions/46258449/cors-error-requests-are-only-supported-for-protocol-schemes-http-etc)

**Comment by somfist** [comment]
Access to XMLHttpRequest at 'http://localhost:4000/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![image](https://user-images.githubusercontent.com/89966037/181917777-23cbee2f-232c-4902-9442-5e5a83274753.png)

**Comment by unchaptered** [comment]
[로컬에서 CORS policy 관련 에러가 발생하는 이유](https://velog.io/@takeknowledge/%EB%A1%9C%EC%BB%AC%EC%97%90%EC%84%9C-CORS-policy-%EA%B4%80%EB%A0%A8-%EC%97%90%EB%9F%AC%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3gk4gyhreu0)

[access-control-origin-header-error-using-axios](https://stackoverflow.com/questions/45975135/access-control-origin-header-error-using-axios)

**Comment by unchaptered** [comment]
- `2022-07-30` 오후 11:22 에러가 해결되었습니다.
- 참석자 : @codeing999   @unchaptered   @dusunax   @somfist 


에러 원인은 `Broccoli-Backend` 에서 Cors 미들웨어가 적용되지 않았었습니다.
